build:
  modules:
    - ninja
  modules_package:
    - eckit:openmpi
    - atlas:openmpi
  dependencies:
    - ecmwf/ecbuild@develop
    - ecmwf/eccodes@develop
    - ecmwf/eckit@develop
    - ecmwf/metkit@develop
    - ecmwf/fckit@develop
    - ecmwf/fdb@develop
    - ecmwf/atlas@develop
    - ecmwf/atlas-orca@develop
    - ecmwf/mir@develop
  parallel: 64
  env:
    - CTEST_PARALLEL_LEVEL=1
    - ECCODES_SAMPLES_PATH=$ECCODES_DIR/share/eccodes/samples
    - ECCODES_DEFINITION_PATH=$ECCODES_DIR/share/eccodes/definitions
