PROGRAM test03

  !> Symbols imported from other modules within the project.
  USE :: DATAKINDS_DEF_MOD, ONLY: JPIB_K

  USE :: FILTER_BASE_MOD,    ONLY: FILTER_BASE_A
  USE :: FILTER_FACTORY_MOD, ONLY: MAKE_FILTER
  USE :: FILTER_FACTORY_MOD, ONLY: DESTROY_FILTER

  USE :: YAML_CORE_UTILS_MOD, ONLY: YAML_CONFIGURATION_T
  USE :: YAML_CORE_UTILS_MOD, ONLY: YAML_NEW_CONFIGURATION_FROM_FILE
  USE :: YAML_CORE_UTILS_MOD, ONLY: YAML_DELETE_CONFIGURATION

  USE :: PARAMETRIZATION_MOD, ONLY: PARAMETRIZATION_T
  USE :: FORTRAN_MESSAGE_MOD, ONLY: FORTRAN_MESSAGE_T

  USE :: GRIB_ENCODER_OPTIONS_MOD, ONLY: GRIB_ENCODER_OPTIONS_T

  USE :: HOOKS_MOD, ONLY: HOOKS_T

IMPLICIT NONE

  !> Test encodr object
  CLASS(FILTER_BASE_A), POINTER :: FILTER => NULL()
  TYPE(HOOKS_T) :: HOOKS
  TYPE(YAML_CONFIGURATION_T) :: CONFIG
  CHARACTER(LEN=32) :: FNAME
  INTEGER(KIND=JPIB_K) :: UNIT
  INTEGER(KIND=JPIB_K) :: OFFSET
  INTEGER(KIND=JPIB_K) :: RET
  INTEGER(KIND=JPIB_K) :: ENCODER_TYPE
  TYPE(FORTRAN_MESSAGE_T) :: MSG
  TYPE(PARAMETRIZATION_T) :: PAR
  LOGICAL :: MATCH

  TYPE(GRIB_ENCODER_OPTIONS_T) :: OPT

  !> Set the unit and offset
  UNIT = 6
  OFFSET = 1
  FNAME = 'config-filter.yaml'

  !> Open the configuration file
  RET = YAML_NEW_CONFIGURATION_FROM_FILE( TRIM(ADJUSTL(FNAME)), CONFIG, HOOKS )
  WRITE(UNIT,'(A,I5)') 'Config open: ', RET

  !> Read the filter
  RET = MAKE_FILTER( FILTER, 'composed', CONFIG, HOOKS )
  WRITE(UNIT,'(A,I5,I5)') 'Create the filter: ', RET

  MSG%PARAM_ID = 1
  MSG%LEVTYPE = 1
  IF ( RET .EQ. 0 ) THEN
    RET = FILTER%MATCH( MSG, PAR, MATCH, HOOKS )
    WRITE(UNIT,'(A,I5,I5)') 'Match the filter: ', MATCH, RET

    RET = FILTER%PRINT( 6_JPIB_K, 1_JPIB_K, HOOKS )
    WRITE(UNIT,'(A,I5,I5)') 'Print the filter: ', RET

  ENDIF

  !> Destroy the encoder object
  RET = DESTROY_FILTER( FILTER, HOOKS )
  WRITE(UNIT,'(A,I5)') 'Destroy the filter: ', RET

  !> Destroy the configuration object
  RET = YAML_DELETE_CONFIGURATION( CONFIG, HOOKS )
  WRITE(UNIT,'(A,I5)') 'Config close', RET

END PROGRAM test03