no-io-info-log:
  encoding-info: true
  verbose: true

dump-fortran-data-reproducer:
  path: './'
  dump-values: true
  verbose: true
  profile: true

grib-msg-to-file:
  path: 'allfields.grib'
  verbose: true
  profile: true

grib-msg-to-multio:
  multio-plans-file: '../multio-ifs-wam-config.yaml'
  verbose: true
  profile: true

grib-header-to-multio:
  multio-plans-file: '../multio-debug-plan.yaml'
  verbose: true
  profile: true

full-grib-header-to-multio:
  multio-plans-file: '../multio-debug-plan.yaml'
  verbose: true
  profile: true

fortran-metadata-to-multio:
  multio-plans-file: '../multio-debug-plan.yaml'
  verbose: true
  profile: true



encoding-rules:

  defaults:
    encode:
      gribEdition: 2

  rules:
    - rule: 'grib1_surfaces_gridded'

      filter: # mandatory
        levtype: ['sfc']
        repres:  ['gridded']
        paramId: [ 31, 34, 49, 78, 134, 136, 137, 142, 144, 151, 165, 166, 168, 169, 175, 176, 177, 178, 179, 180, 181, 205, 228, 228029, 228216, 228218, 228219 ]

      tag: 'GRIB1' # optional

      mapping-rules: # optional
        - recipe:
          from:
            paramId: 31
            level: 0
            levtype: 'sfc'
          to:
            paramId: 160350
            level: 4
            levtype: 'sfc'
            values-scale-factor: 0.01

      # grib-structure: # optional
      #   local-definition-template-number: 2
      #   grid-definition-template-number: 2
      #   product-definition-template-number: 2
      #   data-definition-template-number: 2
      #
      #
      #
      edition: # mandatory
        use-paramId-ecmf: false
        grib-edition: 1

      packing: # optional
        packing-type: 'grid_simple'


encoding-rules:

  default-rules:
    -rule: 'default-rule-that-should-work-almost-always'
       ...

  special-rules:
   - rule: 'grib1_surfaces_gridded'

        # Select messages
      - type: filter
        match:
          levtype: ['sfc']
          repres:  ['gridded']
          paramId: [ 31, 34, 49, 78, 134, 136, 137, 142, 144, 151, 165, 166, 168, 169, 175, 176, 177, 178, 179, 180, 181, 205, 228, 228029, 228216, 228218, 228219 ]

        # This can be used to convert prefix to levtype
      - type: mapping
        recipes:
          - recipe:
            from:
              paramId: 31
              level: 0
              levtype: 'sfc'
            to:
              paramId: 160350
              level: 4
              levtype: 'sfc'
              values-scale-factor: 0.01

        # Sample to be loaded fro this rule (should be shared between the rules)
      - type: load-sample
        sample-path: <>
        sample-name: <>
        options:
          strip-values: true
          strip-bitmask: true
          strip-section2: true
          strip-section3: true

        # Everything that can be done once should be done once and then cached.
        # First time a message with a specific hash arrive for the first time (not in the map),
        # The sample is loaded and preset and then added to the map.
      - type: lazy-preset
        presets:

          - type: local-definition-section
            template-number: [2, <metkit::map-name> ]
            options:
              bla: <specific configurations to be set for the grib2 section2 number 2>

          - type: grid-definition-section
            template-number:  [40, <metkit::map-name> ]
            options:
              bla: ...

          - type: product-definition-section
            template-number: [ 1, <metkit::map-name> ]
            options:
              bla: ...

          - type: data-definition-section
            template-number: [ 2, <metkit::map-name> ]
            options:
              bla: ...

        # When a fully preset template is in the map, the only euntime change are the values and the time configuration.
        # Values may need a scaling due to the mapping (i.e. change units)
      - type: runtime-configurations
        runtime-cfg:
          - type: time-configuration
            options:
              bla: ...

          - type: values-configuration
            options:
              bla: ...


      - type: sink
        sinks:
          - type: grib-msg-to-file
            options:
              bla: ...

          - type: grib-msg-to-multio
            option:
              bla: ...

          - type: grib-msg-to-multio
            option:
              bla: ...


      # grib-structure: # optional
      #   local-definition-template-number: 2
      #   grid-definition-template-number: 2
      #   product-definition-template-number: 2
      #   data-definition-template-number: 2
      #
      #
      #
      edition: # mandatory
        use-paramId-ecmf: false
        grib-edition: 1

      packing: # optional
        packing-type: 'grid_simple'


    - rule: 'grib1_height_level_gridded'
      filter:
        levtype: ['hl']
        repres: ['gridded']
        paramId: [ 228246, 228247 ]

      encode:
        gribEdition: 1
        packingType: 'grid_simple'


    - rule: 'grib2_sol_gridded'
      filter:
        levtype: ['sol']
        repres: ['gridded']
        paramId: [ 33, 238 ]

      encode:
        gribEdition: 2
        packingType: 'grid_simple'


    - rule: 'grib2_surfaces_gridded'
      filter:
        levtype: ['sfc']
        repres: ['gridded']
        paramId: [ 75, 76, 77, 129, 130, 131, 132, 133, 135, 138, 155, 156, 157, 164, 167, 246, 247, 248, 3020, 3062, 162071, 162072, 228003, 228050, 228058, 228143, 228144, 228164, 228221, 228228, 228235, 228236, 228246, 228247, 231001, 231002, 231013, 260015, 260199, 260227, 260228, 260238, 260360, 260510, 262121 ]

      encode:
        gribEdition: 2
        packingType: 'grid_simple'


    - rule: 'grib1_ptv_levels_gridded'
      filter:
        levtype: [ 'pl', 'pv', 'pt' ]
        repres: ['gridded']
        paramId: [ 129, 130, 131, 132, 133, 138, 155, 157 ]

      encode:
        gribEdition: 1
        packingType: 'grid_simple'


    - rule: 'grib2_ptv_levels_gridded'
      filter:
        levtype: [ 'pl', 'pv', 'pt' ]
        repres: ['gridded']
        paramId: [ 31, 34, 49, 75, 76, 77, 78, 134, 135, 136, 137, 142, 144, 151, 156, 164, 165, 166, 167, 168, 169, 175, 176, 177, 178, 179, 180, 181, 205, 228, 246, 247, 248, 3020, 3062, 162071, 162072, 228003, 228029, 228050, 228058, 228143, 228144, 228164, 228216, 228218, 228219, 228221, 228228, 228235, 228236, 231001, 231002, 231013, 260015, 260199, 260227, 260228, 260238, 260360, 260510, 262121 ]

      encode:
        gribEdition: 2
        packingType: 'grid_simple'


    - rule: 'grib2_ml_gridded'
      filter:
        levtype: ['ml']
        repres: ['gridded']
        paramId: [ 31, 34, 49, 75, 76, 77, 78, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 142, 144, 151, 155, 156, 157, 164, 165, 166, 167, 168, 169, 175, 176, 177, 178, 179, 180, 181, 205, 228, 246, 247, 248, 3020, 3062, 162071, 162072, 228003, 228029, 228050, 228058, 228143, 228144, 228164, 228216, 228218, 228219, 228221, 228228, 228235, 228236, 231001, 231002, 231013, 260015, 260199, 260227, 260228, 260238, 260360, 260510, 262121 ]

      encode:
        gribEdition: 2
        packingType: 'grid_simple'


    - rule: 'grib2_wam_int_gridded'
      filter:
        levtype: ['sfc']
        repres: ['gridded']
        paramId: [ 140221, 140229, 140230, 140231, 140232 ]

      encode:
        gribEdition: 2
        packingType: 'grid_simple'


    - rule: 'grib2_ml_spherical_harmonics'
      filter:
        levtype: ['ml']
        repres: ['spherical_harmonics']
        paramId: [ 77, 135, 138, 152, 155 ]

      encode:
        gribEdition: 2
        packingType: 'spectral_complex'


    - rule: 'grib2_pl_spherical_harmonics'
      filter:
        levtype: ['pl']
        repres: ['spherical_harmonics']
        paramId: [ 138, 155 ]

      encode:
        gribEdition: 2
        packingType: 'spectral_complex'
