MODULE GRIB2_MESSAGE_MOD
IMPLICIT NONE

TYPE, ABSTRACT :: RUNTIME_OP_A

CONTAINS

    PROCEDURE(ENCODE_IF), PASS, DEFERRED :: ENCODE
    PROCEDURE(FREE_IF),   PASS, DEFERRED :: FREE

END TYPE

TYPE :: RUNTIME_OP_CONTAINER_T

  PRIVATE

  CLASS(RUNTIME_OP_A), POINTER :: ENCODE_OP => NULL()

CONTAINS

  PROCEDURE, PUBLIC, PASS, NON_OVERRIDABLE :: ENCODE => RUNTIME_OP_CONTAINER_INIT
  PROCEDURE, PUBLIC, PASS, NON_OVERRIDABLE :: ENCODE => RUNTIME_OP_CONTAINER_ENCODE
  PROCEDURE, PUBLIC, PASS, NON_OVERRIDABLE :: FREE   => RUNTIME_OP_CONTAINER_FREE

END TYPE



CONTAINS


END MODULE GRIB2_MESSAGE_MOD