MODULE GRIB2_ENCODER_MOD

  USE :: SAMPLE_LOADER_MOD,          ONLY: SAMPLE_LOADER_T
  USE :: GRIB2_SECTION1_FACTORY_MOD, ONLY: GRIB2_SECTION1_BASE_T
  USE :: GRIB2_SECTION2_FACTORY_MOD, ONLY: GRIB2_SECTION2_BASE_T
  USE :: GRIB2_SECTION3_FACTORY_MOD, ONLY: GRIB2_SECTION3_BASE_T
  USE :: GRIB2_SECTION4_FACTORY_MOD, ONLY: GRIB2_SECTION4_BASE_T
  USE :: GRIB2_SECTION5_FACTORY_MOD, ONLY: GRIB2_SECTION5_BASE_T
  USE :: GRIB_MESSAGE_MOD, ONLY: GRIB_MESSAGE_A

IMPLICIT NONE



TYPE, EXTENDS(GRIB_ENCODER_A) :: GRIB2_ENCODER_T

  !> Default visibility of the class members
  PRIVATE

  CLASS(SAMPLE_LOADER_A),     POINTER :: SAMPLE_LOADER => NULL()
  CLASS(GRIB_SECTION_BASE_A), POINTER :: SEC0 => NULL()
  CLASS(GRIB_SECTION_BASE_A), POINTER :: SEC1 => NULL()
  CLASS(GRIB_SECTION_BASE_A), POINTER :: SEC2 => NULL()
  CLASS(GRIB_SECTION_BASE_A), POINTER :: SEC3 => NULL()
  CLASS(GRIB_SECTION_BASE_A), POINTER :: SEC4 => NULL()
  CLASS(GRIB_SECTION_BASE_A), POINTER :: SEC5 => NULL()
  CLASS(GRIB_SECTION_BASE_A), POINTER :: SEC6 => NULL()

CONTAINS

  PROCEDURE, PUBLIC, PASS, NON_OVERRRIDABLE :: INIT => GRIB2_MESSAGE_INIT

  PROCEDURE, PUBLIC, PASS, NON_OVERRRIDABLE :: ALLOCATE => GRIB2_MESSAGE_ALLOCATE

  PROCEDURE, PUBLIC, PASS, NON_OVERRRIDABLE :: PRESET => GRIB2_MESSAGE_PRESET

  PROCEDURE, PUBLIC, PASS, NON_OVERRRIDABLE :: RUNTIME => GRIB2_MESSAGE_RUNTIME

  PROCEDURE, PUBLIC, PASS, NON_OVERRRIDABLE :: FREE => GRIB2_MESSAGE_FREE

END TYPE


CONTAINS


SUBROUTINE GRIB2_MESSAGE_INIT( THIS, PARAMS, CFG, VERBOSE )

  USE :: GRIB2_SECTIONS_FACTORY_MOD, ONLY: GRIB2_SECTIONS_FACTORY

IMPLICIT NONE

! Dummy arguments
CLASS(GRIB2_ENCODER_T),     INTENT(INOUT) :: THIS
TYPE(PARAMS_T),             INTENT(IN)    :: PARAMS
TYPE(YAML_CONFIGURATION_T), INTENT(IN)    :: CFG
LOGICAL,                    INTENT(IN)    :: VERBOSE

! Initialize the sections
! CALL SAMPLE_LOADER_FACTORY( THIS%SAMPLE_LOADER, PARAMS, CFG, VERBOSE )
CALL GRIB2_FACTORY( THIS%SEC0, 0, PARAMS, CFG, VERBOSE )
CALL GRIB2_FACTORY( THIS%SEC1, 1, PARAMS, CFG, VERBOSE )
CALL GRIB2_FACTORY( THIS%SEC2, 2, PARAMS, CFG, VERBOSE )
CALL GRIB2_FACTORY( THIS%SEC3, 3, PARAMS, CFG, VERBOSE )
CALL GRIB2_FACTORY( THIS%SEC4, 4, PARAMS, CFG, VERBOSE )
CALL GRIB2_FACTORY( THIS%SEC5, 5, PARAMS, CFG, VERBOSE )
CALL GRIB2_FACTORY( THIS%SEC6, 6, PARAMS, CFG, VERBOSE )

END SUBROUTINE GRIB2_MESSAGE_INIT



SUBROUTINE GRIB2_MESSAGE_ALLOCATE( THIS, PARAMS, METADATA, VERBOSE )

IMPLICIT NONE

! Dummy arguments
CLASS(GRIB2_ENCODER_T), INTENT(IN)    :: THIS
TYPE(PARAMS_T),         INTENT(IN)    :: PARAMS
CLASS(METADATA_BASE_T), INTENT(INOUT) :: METADATA
LOGICAL,                INTENT(IN)    :: VERBOSE

! Initialize the sections
! CALL THIS%SAMPLE_LOADER%LOAD( PARAMS, METADATA, VERBOSE )
CALL THIS%SEC0%ALLOCATE( PARAMS, METADATA, VERBOSE )
CALL THIS%SEC1%ALLOCATE( PARAMS, METADATA, VERBOSE )
CALL THIS%SEC2%ALLOCATE( PARAMS, METADATA, VERBOSE )
CALL THIS%SEC3%ALLOCATE( PARAMS, METADATA, VERBOSE )
CALL THIS%SEC4%ALLOCATE( PARAMS, METADATA, VERBOSE )
CALL THIS%SEC5%ALLOCATE( PARAMS, METADATA, VERBOSE )
CALL THIS%SEC6%ALLOCATE( PARAMS, METADATA, VERBOSE )

END SUBROUTINE GRIB2_MESSAGE_ALLOCATE


SUBROUTINE GRIB2_MESSAGE_PRESET( THIS, PARAMS, METADATA, VERBOSE )

IMPLICIT NONE

! Dummy arguments
CLASS(GRIB2_ENCODER_T), INTENT(IN)    :: THIS
TYPE(PARAMS_T),         INTENT(IN)    :: PARAMS
CLASS(METADATA_BASE_T), INTENT(INOUT) :: METADATA
LOGICAL,                INTENT(IN)    :: VERBOSE

! Initialize the sections
CALL THIS%SEC0%PRESET( PARAMS, METADATA, VERBOSE )
CALL THIS%SEC1%PRESET( PARAMS, METADATA, VERBOSE )
CALL THIS%SEC2%PRESET( PARAMS, METADATA, VERBOSE )
CALL THIS%SEC3%PRESET( PARAMS, METADATA, VERBOSE )
CALL THIS%SEC4%PRESET( PARAMS, METADATA, VERBOSE )
CALL THIS%SEC5%PRESET( PARAMS, METADATA, VERBOSE )
CALL THIS%SEC6%PRESET( PARAMS, METADATA, VERBOSE )

END SUBROUTINE GRIB2_MESSAGE_PRESET


SUBROUTINE GRIB2_MESSAGE_RUNTIME( THIS, PARAMS, RUNTIME_OPS, VERBOSE )

IMPLICIT NONE

! Dummy arguments
CLASS(GRIB2_ENCODER_T),                                  INTENT(INOUT) :: THIS
TYPE(PARAMS_T),                                          INTENT(IN)    :: PARAMS
TYPE(RUNTIME_OP_CONTAINER_T), DIMENSION(:), ALLOCATABLE, INTENT(IN)    :: RUNTIME_OPS
LOGICAL,                                                 INTENT(IN)    :: VERBOSE

! Local variables
INTEGER(KIND=JPIB_K) :: CNT
INTEGER(KIND=JPIB_K) :: N_RUNTIME_OPS
INTEGER(KIND=JPIB_K), DIMENSION(0:6) :: LO
INTEGER(KIND=JPIB_K), DIMENSION(0:6) :: HI

! Initialize the sections
CNT = 0

CALL THIS%SEC0%NUMBER_OF_RUNTIME_OPS( PARAMS, N_RUNTIME_OPS, VERBOSE )
LO(0) = CNT + 1
CNT = CNT + N_RUNTIME_OPS
HI(0) = CNT

CALL THIS%SEC1%NUMBER_OF_RUNTIME_OPS( PARAMS, N_RUNTIME_OPS, VERBOSE )
LO(1) = CNT + 1
CNT = CNT + N_RUNTIME_OPS
HI(1) = CNT

CALL THIS%SEC2%NUMBER_OF_RUNTIME_OPS( PARAMS, N_RUNTIME_OPS, VERBOSE )
LO(2) = CNT + 1
CNT = CNT + N_RUNTIME_OPS
HI(2) = CNT

CALL THIS%SEC3%NUMBER_OF_RUNTIME_OPS( PARAMS, N_RUNTIME_OPS, VERBOSE )
LO(3) = CNT + 1
CNT = CNT + N_RUNTIME_OPS
HI(3) = CNT

CALL THIS%SEC4%NUMBER_OF_RUNTIME_OPS( PARAMS, N_RUNTIME_OPS, VERBOSE )
LO(4) = CNT + 1
CNT = CNT + N_RUNTIME_OPS
HI(4) = CNT

CALL THIS%SEC5%NUMBER_OF_RUNTIME_OPS( PARAMS, N_RUNTIME_OPS, VERBOSE )
LO(5) = CNT + 1
CNT = CNT + N_RUNTIME_OPS
HI(5) = CNT

CALL THIS%SEC6%NUMBER_OF_RUNTIME_OPS( PARAMS, N_RUNTIME_OPS, VERBOSE )
LO(6) = CNT + 1
CNT = CNT + N_RUNTIME_OPS
HI(6) = CNT

! Allocate the runtime ops
ALLOCATE(RUNTIME_OPS(CNT))

! Initialize the sections
CALL THIS%SEC1%GET_RUNTIME_OPS( PARAMS, MSG, RUNTIME_OPS(LO(0):HI(0)), VERBOSE )
CALL THIS%SEC1%GET_RUNTIME_OPS( PARAMS, MSG, RUNTIME_OPS(LO(1):HI(1)), VERBOSE )
CALL THIS%SEC2%GET_RUNTIME_OPS( PARAMS, MSG, RUNTIME_OPS(LO(2):HI(2)), VERBOSE )
CALL THIS%SEC3%GET_RUNTIME_OPS( PARAMS, MSG, RUNTIME_OPS(LO(3):HI(3)), VERBOSE )
CALL THIS%SEC4%GET_RUNTIME_OPS( PARAMS, MSG, RUNTIME_OPS(LO(4):HI(4)), VERBOSE )
CALL THIS%SEC5%GET_RUNTIME_OPS( PARAMS, MSG, RUNTIME_OPS(LO(5):HI(5)), VERBOSE )
CALL THIS%SEC1%GET_RUNTIME_OPS( PARAMS, MSG, RUNTIME_OPS(LO(6):HI(6)), VERBOSE )

END SUBROUTINE GRIB2_MESSAGE_RUNTIME


SUBROUTINE GRIB2_MESSAGE_FREE( THIS, VERBOSE )

  USE :: GRIB2_SECTION1_FACTORY_MOD, ONLY: GRIB2_SECTION1_FACTORY
  USE :: GRIB2_SECTION2_FACTORY_MOD, ONLY: GRIB2_SECTION2_FACTORY
  USE :: GRIB2_SECTION3_FACTORY_MOD, ONLY: GRIB2_SECTION3_FACTORY
  USE :: GRIB2_SECTION4_FACTORY_MOD, ONLY: GRIB2_SECTION4_FACTORY
  USE :: GRIB2_SECTION5_FACTORY_MOD, ONLY: GRIB2_SECTION5_FACTORY

IMPLICIT NONE

! Dummy arguments
CLASS(GRIB2_ENCODER_T),     INTENT(INOUT) :: THIS
LOGICAL,                    INTENT(IN)    :: VERBOSE

! Initialize the sections
CALL THIS%SAMPLE_LOADER%FREE( VERBOSE )
CALL THIS%SEC0%FREE( VERBOSE )
CALL THIS%SEC1%FREE( VERBOSE )
CALL THIS%SEC2%FREE( VERBOSE )
CALL THIS%SEC3%FREE( VERBOSE )
CALL THIS%SEC4%FREE( VERBOSE )
CALL THIS%SEC5%FREE( VERBOSE )
CALL THIS%SEC6%FREE( VERBOSE )

DEALLOCATE( THIS%SAMPLE_LOADER )
DEALLOCATE( THIS%SEC0 )
DEALLOCATE( THIS%SEC1 )
DEALLOCATE( THIS%SEC2 )
DEALLOCATE( THIS%SEC3 )
DEALLOCATE( THIS%SEC4 )
DEALLOCATE( THIS%SEC5 )
DEALLOCATE( THIS%SEC6 )

NULLIFY( THIS%SAMPLE_LOADER )
NULLIFY( THIS%SEC0 )
NULLIFY( THIS%SEC1 )
NULLIFY( THIS%SEC2 )
NULLIFY( THIS%SEC3 )
NULLIFY( THIS%SEC4 )
NULLIFY( THIS%SEC5 )
NULLIFY( THIS%SEC6 )

END SUBROUTINE GRIB2_MESSAGE_FREE


END MODULE GRIB2_ENCODER_MOD