#pragma once


// Matchers
#define ENABLE_NO_FILTER_MATCHER
#define ENABLE_DAILY_HOURS_MATCHER
#define ENABLE_DAILY_CUSTOM_MATCHER


// Operations
#define ENABLE_ACCUMULATE_OPERATION
#define ENABLE_AVERAGE_OPERATION
#define ENABLE_FLUXAVERAGE_OPERATION
#define ENABLE_INSTANT_OPERATION
#define ENABLE_MAXIMUM_OPERATION
#define ENABLE_MINIMUM_OPERATION
#define ENABLE_DIFFERENCE_OPERATION
#define ENABLE_VARIANCE_OPERATION
#define ENABLE_STDDEV_OPERATION
