#pragma once


// Matchers
#define __ENABLE_NO_FILTER_MATCHER__
#define __ENABLE_DAILY_HOURS_MATCHER__
#define __ENABLE_DAILY_CUSTOM_MATCHER__


// Operations
#define __ENABLE_ACCUMULATE_OPERATION__
#define __ENABLE_AVERAGE_OPERATION__
#define __ENABLE_FLUXAVERAGE_OPERATION__
#define __ENABLE_INSTANT_OPERATION__
#define __ENABLE_MAXIMUM_OPERATION__
#define __ENABLE_MINIMUM_OPERATION__
#define __ENABLE_DEFFERENCE_OPERATION__
#define __ENABLE_VARIANCE_OPERATION__
#define __ENABLE_STDDEV_OPERATION__


