MODULE GRIB2_ENCODER_MOD
IMPLICIT NONE


TYPE, EXTENDS(ENCODER_BASE_T) :: GRIB2_ENCODER_T

  !> Default visibility of the class
  PRIVATE

  !> Sample
  CLASS(SAMPLE_LOADER_T), POINTER :: SAMPLE_LOADER => NULL()

  !> Preset actions
  CLASS(GRIB2_SECTION1_PRESET_ENCODER_T), POINTER :: SECTION1_PRESET_ENCODER_ => NULL()
  CLASS(GRIB2_SECTION2_PRESET_ENCODER_T), POINTER :: SECTION2_PRESET_ENCODER_ => NULL()
  CLASS(GRIB2_SECTION3_PRESET_ENCODER_T), POINTER :: SECTION3_PRESET_ENCODER_ => NULL()
  CLASS(GRIB2_SECTION4_PRESET_ENCODER_T), POINTER :: SECTION4_PRESET_ENCODER_ => NULL()
  CLASS(GRIB2_SECTION5_PRESET_ENCODER_T), POINTER :: SECTION5_PRESET_ENCODER_ => NULL()

  !> Runtime actions
  CLASS(GRIB2_SECTION4_RUNTIME_ENCODER_T), POINTER :: SECTION4_RUNTIME_ENCODER_ => NULL()

CONTAINS

  !> Initialize encoders (read configuration from yaml and allocate/initialize all the fields)
  PROCEDURE, PUBLIC, NON_OVERRIDABLE, PASS :: INIT   => ENCODER_INIT

  !> Load and preset the grib sample
  PROCEDURE, PUBLIC, NON_OVERRIDABLE, PASS :: PRESET => ENCODER_PRESET

  !> Finalize the encoding of the grib sample
  PROCEDURE, PUBLIC, NON_OVERRIDABLE, PASS :: ENCODE => ENCODER_ENCODE

  !> Free the memory allocated by the encoder
  PROCEDURE, PUBLIC, NON_OVERRIDABLE, PASS :: FREE   => ENCODER_FREE
END TYPE

CONTAINS

END MODULE GRIB2_ENCODER_MOD