MODULE GRIB_SECTION_MOD

IMPLICIT NONE



TYPE, ABSTRACT :: GRIB_SECTION_BASE_A

CONTAINS

  PUBLIC(GRIB_SECTION_INIT_IF),                  DEFERRED, PASS, PUBLIC :: INIT
  PUBLIC(GRIB_SECTION_ALLOCATE_IF),              DEFERRED, PASS, PUBLIC :: ALLOCATE
  PUBLIC(GRIB_SECTION_PRESET_IF),                DEFERRED, PASS, PUBLIC :: PRESET
  PUBLIC(GRIB_SECTION_NUMBER_OF_RUNTIME_OPS_IF), DEFERRED, PASS, PUBLIC :: NUMBER_OF_RUNTIME_OPS
  PUBLIC(GRIB_SECTION_GET_RUNTIME_OPS_IF),       DEFERRED, PASS, PUBLIC :: GET_RUNTIME_OPS
  PUBLIC(GRIB_SECTION_FREE_IF),                  DEFERRED, PASS, PUBLIC :: FREE

END TYPE


ABSTACT INTERFACE
__THREAD_SAFE__ FUNCTION GRIB_SECTION_INIT_IF( THIS, PARAMS, CFG, VERBOSE ) RESULT(RET)
  IMPORT :: GRIB_SECTION_BASE_A
IMPLICIT NONE
! Dummy arguments
CLASS(GRIB_SECTION_BASE_A), INTENT(INOUT) :: THIS
TYPE(PARAMS_T),             INTENT(IN)    :: PARAMS
TYPE(YAML_CONFIGURATION_T), INTENT(IN)    :: CFG
LOGICAL,                    INTENT(IN)    :: VERBOSE
! Function result
INTEGER(KIND=JPIB_K) :: RET
END FUNCTION GRIB_SECTION_INIT_IF

__THREAD_SAFE__ FUNCTION GRIB_SECTION_ALLOCATE_IF( THIS, PARAMS, METADATA, VERBOSE ) RESULT(RET)
  IMPORT :: GRIB_SECTION_BASE_A
IMPLICIT NONE
! Dummy arguments
CLASS(GRIB_SECTION_BASE_A), INTENT(IN)    :: THIS
TYPE(PARAMS_T),             INTENT(IN)    :: PARAMS
CLASS(METADATA_BASE_T),     INTENT(INOUT) :: METADATA
LOGICAL,                    INTENT(IN)    :: VERBOSE
! Function result
INTEGER(KIND=JPIB_K) :: RET
END FUNCTION GRIB_SECTION_ALLOCATE_IF

__THREAD_SAFE__ FUNCTION GRIB_SECTION_PRESET_IF( THIS, PARAMS, METADATA, VERBOSE ) RESULT(RET)
  IMPORT :: GRIB_SECTION_BASE_A
IMPLICIT NONE
! Dummy arguments
CLASS(GRIB_SECTION_BASE_A), INTENT(IN)    :: THIS
TYPE(PARAMS_T),             INTENT(IN)    :: PARAMS
CLASS(METADATA_BASE_T),     INTENT(INOUT) :: METADATA
LOGICAL,                    INTENT(IN)    :: VERBOSE
! Function result
INTEGER(KIND=JPIB_K) :: RET
END FUNCTION GRIB_SECTION_PRESET_IF

__THREAD_SAFE__ FUNCTION GRIB_SECTION_GET_RUNTIME_OPS_IF( THIS, PARAMS, RUNTIME_OPS, VERBOSE ) RESULT(RET)
  IMPORT :: GRIB_SECTION_BASE_A
IMPLICIT NONE
! Dummy arguments
CLASS(GRIB_SECTION_BASE_A),                                  INTENT(INOUT) :: THIS
TYPE(PARAMS_T),                                          INTENT(IN)    :: PARAMS
TYPE(RUNTIME_OP_CONTAINER_T), DIMENSION(:), ALLOCATABLE, INTENT(IN)    :: METADATA
LOGICAL,                                                 INTENT(IN)    :: VERBOSE
! Function result
INTEGER(KIND=JPIB_K) :: RET
END FUNCTION GRIB_SECTION_GET_RUNTIME_OPS_IF

__THREAD_SAFE__ FUNCTION GRIB_SECTION_NUMBER_OF_RUNTIME_OPS_IF( THIS, PARAMS, HAS_RUNTIME_OPS, VERBOSE ) RESULT(RET)
  IMPORT :: GRIB_SECTION_BASE_A
IMPLICIT NONE
! Dummy arguments
CLASS(GRIB_SECTION_BASE_A), INTENT(INOUT) :: THIS
TYPE(PARAMS_T),             INTENT(IN)    :: PARAMS
LOGICAL,                    INTENT(OUT)   :: HAS_RUNTIME_OPS
LOGICAL,                    INTENT(IN)    :: VERBOSE
! Function result
INTEGER(KIND=JPIB_K) :: RET
END FUNCTION GRIB_SECTION_NUMBER_OF_RUNTIME_OPS_IF


__THREAD_SAFE__ FUNCTION GRIB_SECTION_FREE_IF( THIS ) RESULT(RET)
  IMPORT :: GRIB_SECTION_BASE_A
IMPLICIT NONE
! Dummy arguments
CLASS(GRIB_SECTION_BASE_A), INTENT(INOUT) :: THIS
! Function result
INTEGER(KIND=JPIB_K) :: RET
END FUNCTION GRIB_SECTION_FREE_IF

END INTERFACE

END MODULE GRIB_SECTION_MOD