MODULE RULES_MOD
IMPLICIT NONE


TYPE :: MAPPING_T

  !> Default visibility of the module
  PRIVATE

  !> Filters of the rule
  CLASS(FILTER_BASE_A), POINTER :: FILTER_ => NULL()

  !>
  CLASS(MSG_UPDATER_BASE_A), POINTER :: MSG_UPDATER_ => NULL()
  CLASS(PAR_UPDATER_BASE_A), POINTER :: PAR_UPDATER_ => NULL()
  CLASS(OPT_UPDATER_BASE_A), POINTER :: OPT_UPDATER_ => NULL()

END TYPE

TYPE :: RULE_T

  !> Default visibility of the module
  PRIVATE

  !> Filters of the rule
  CLASS(FILTER_BASE_A), POINTER :: FILTER_ => NULL()

  !> Mapping rule
  TYPE(MAPPING_CONTAINER_T), DIMENSION(:), POINTER :: MAPPING_ => NULL()

  !> Encoder rule
  CLASS(GRIB_SECTION_BASE_A), POINTER :: ENCODER_ => NULL()

CONTAINS

  PROCEDURE, PASS, PUBLIC, NON_OVERRIDABLE :: INIT            => RULE_INIT
  PROCEDURE, PASS, PUBLIC, NON_OVERRIDABLE :: MATCH           => RULE_MATCH
  PROCEDURE, PASS, PUBLIC, NON_OVERRIDABLE :: HAS_MSG_MAPPING => RULE_HAS_MSG_MAPPING
  PROCEDURE, PASS, PUBLIC, NON_OVERRIDABLE :: HAS_PAR_MAPPING => RULE_HAS_PAR_MAPPING
  PROCEDURE, PASS, PUBLIC, NON_OVERRIDABLE :: GET_MSG_MAPPING => RULE_GET_MSG_MAPPING
  PROCEDURE, PASS, PUBLIC, NON_OVERRIDABLE :: GET_PAR_MAPPING => RULE_GET_PAR_MAPPING
  PROCEDURE, PASS, PUBLIC, NON_OVERRIDABLE :: GET_ENCODER     => RULE_GET_ENCODER
  PROCEDURE, PASS, PUBLIC, NON_OVERRIDABLE :: FREE            => RULE_FREE

END TYPE

!> Whitelist of public symbols
PUBLIC :: RULE_T
PUBLIC :: MAKE_RULE
PUBLIC :: MAKE_RULES
PUBLIC :: DESTROY_RULE
PUBLIC :: DESTROY_RULES

CONTAINS

END MODULE RULES_MOD

