MODULE GRIB2_ENCODER_MOD

  USE :: GRIB_MESSAGE_MOD, ONLY: GRIB_MESSAGE_A

IMPLICIT NONE



TYPE, ABSTRACT :: GRIB_ENCODER_BASE_A


CONTAINS

  PROCEDURE(INIT_IF),          PUBLIC, PASS, DEFERRED :: INIT
  PROCEDURE(ALLOCATE_IF),      PUBLIC, PASS, DEFERRED :: ALLOCATE
  PROCEDURE(PRESET_IF),        PUBLIC, PASS, DEFERRED :: PRESET
  PROCEDURE(RUNTIME_IF),       PUBLIC, PASS, DEFERRED :: RUNTIME
  PROCEDURE(TO_BE_ENCODED_IF), PUBLIC, PASS, DEFERRED :: TO_BE_ENCODED
  PROCEDURE(FREE_IF),          PUBLIC, PASS, DEFERRED :: FREE

END TYPE

END MODULE GRIB2_ENCODER_MOD